# Generated by Django 5.1.1 on 2024-09-26 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, help_text='Comment must not exceed 300 characters.', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
